version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_USER_API_URL=${REACT_APP_USER_API_URL}
      - REACT_APP_COURSE_API_URL=${REACT_APP_COURSE_API_URL}
    depends_on:
      - user-service
      - course-service
    restart: unless-stopped

  user-service:
    build: ./user-service
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=${MONGO_URI}
      - NOTIFICATION_SERVICE_URL=${NOTIFICATION_SERVICE_URL}
      - MONGO_ROOT_PASSWORD=mongodb-password
    depends_on:
      - mongo
      - notification-service
    restart: unless-stopped

  course-service:
    build: ./course-service
    ports:
      - "5002:5002"
    environment:
      - MONGO_URI=${MONGO_URI}
      - MONGO_ROOT_PASSWORD=mongodb-password
    depends_on:
      - mongo
    restart: unless-stopped

  notification-service:
    build: ./notification-service
    ports:
      - "5003:5003"
    environment:
      - SENDER_EMAIL=${SENDER_EMAIL}
      - SENDER_PASSWORD=${SENDER_PASSWORD}
    restart: unless-stopped

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongodb-password
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
