apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels: { app: user-service }
  template:
    metadata:
      labels: { app: user-service }
    spec:
      containers:
      - name: user-service
        image: sriniv7654/busybox2:login-page-user-service
        ports:
        - containerPort: 5001
        env:
        - name: NOTIFICATION_SERVICE_URL
          valueFrom:
            configMapKeyRef: { name: login-page-config, key: NOTIFICATION_SERVICE_URL }
        - name: MONGO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef: { name: login-page-secrets, key: MONGO_ROOT_PASSWORD }
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef: { name: login-page-config, key: MONGO_URI }
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector: { app: user-service }
  ports:
  - port: 5001
    targetPort: 5001